# Makefile for Tetris Game

# Compiler
CXX = g++

# Compiler flags
CXXFLAGS = -Wall -g

# Build target executable
TARGET = Game

# Source files
SRCS = Game.cpp Board.cpp Piece.cpp ThemeManager.cpp

# Object files
OBJS = $(SRCS:.cpp=.o)

# Build all
all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

# To obtain object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean
clean:
	rm -f $(OBJS) $(TARGET)
